apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default 
  name: gang-scheduler
  labels:
    app: gang-scheduler
    component: gang-scheduler
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gang-scheduler
subjects:
- kind: ServiceAccount
  name: gang-scheduler
  namespace: default 
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: system:kube-scheduler